### ISSUE TITLE
Dont start 

### ISSUE THREAD

**Issue by Zakidushnnik** [veeenu/darksoulsiii-practice-tool#18]
16:05:50 [INFO] Version 1 15 0
16:05:50 [INFO] Waiting on memory: Invalid param base address
16:05:50 [INFO] Waiting on memory: Invalid param base address
16:05:51 [INFO] Waiting on memory: Invalid param base address
16:05:51 [INFO] Waiting on memory: Invalid param base address
16:05:52 [INFO] Waiting on memory: Invalid param base address
16:05:52 [INFO] Waiting on memory: Invalid param base address
16:05:55 [INFO] Initialized
 
in log. i run with admin
folder in C:/practicetool

**Comment by veeenu** [comment]
From this message I have no idea what is going on. Please provide more details. Make sure you have no antivirus running and [post a `DEBUG` level log](https://github.com/veeenu/darksoulsiii-practice-tool#i-found-a-bug-what-do-i-do)
