### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by zFireKami** [veeenu/darksoulsiii-practice-tool#19]
the app just open and instantly closes

**Comment by zFireKami** [comment]
i'm also using w11 build 22h2

**Comment by zFireKami** [comment]
22:17:50 [DEBUG] (1) libjdsd_dsiii_practice_tool: "TOML configuration parse error: data did not match any variant of untagged enum CfgCommand for key `commands` at line 34 column 1"
22:17:50 [INFO] Version 1 8 0
22:17:50 [DEBUG] (1) libds3::pointers: BaseAddresses {
    world_chr_man: 5443342168,
    world_chr_man_dbg: 5443342456,
    menu_man: 5443224536,
    base_a: 5443175016,
    base_d: 5443189592,
    sprj_debug_event: 5443153544,
    debug: 5443342409,
    grend: 5441173000,
    base_hbd: 5443333216,
    map_item_man: 5443173880,
    spawn_item_func_ptr: 5376795184,
    param: 5443460560,
    format_string: 5412038976,
    no_logo: 5381122767,
    xa: 8064,
}
22:17:50 [INFO] Initialized
22:17:50 [ERROR] thread '<unnamed>' panicked at 'D3D11CreateDeviceAndSwapChain failed: Error { code: 0x80070005, message: Acesso negado. }': lib\hudhook\src\hooks\dx11.rs:335

**Comment by veeenu** [comment]
Hi! You have an error in your configuration file, or you used the file from a previous version of the tool and it's in an incompatible format. Please delete it and use the one bundled in the release zip. Please let me know if this fixes your problem!
