### ISSUE TITLE
Ds3 practice tool doesn't run on info log_level

### ISSUE THREAD

**Issue by WhiteXenomorph** [veeenu/darksoulsiii-practice-tool#3]
I've started using the practice tool 3 days ago or so, first 2 days was working great, but yesterday stopped working, running the game and then the tool wasn't making appear the command console and I couldn't do anything with it. Doing the steps various times doesn't change the result.

[jdsd_dsiii_practice_tool.log](https://github.com/veeenu/darksoulsiii-practice-tool/files/5275996/jdsd_dsiii_practice_tool.log)

I should have attached the log, but in case i messed up here is the text of the log:

12:23:38 [INFO] Loading configuration from "\\\\?\\C:\\Users\\matt\\Desktop\\jdsd_dsiii_practice_tool\\jdsd_dsiii_practice_tool.toml"
12:23:38 [INFO] Logging to "\\\\?\\C:\\Users\\matt\\Desktop\\jdsd_dsiii_practice_tool\\jdsd_dsiii_practice_tool.log"
12:23:38 [ERROR] Hook errored: Error("D3D11CreateDeviceAndSwapChain failed 887a0001")

Today I tried running the tool with the debug log_level and the tool worked fine, trying again with info log_level gives me the same error again.

**Comment by veeenu** [comment]
Hi, and thank you for reporting the issue!

I just released a [new patch version](https://github.com/veeenu/darksoulsiii-practice-tool/releases/tag/1.1.1) which should hopefully solve your problem. Could you please try and reproduce the error with this?

**Comment by WhiteXenomorph** [comment]
It works! Now I can also see the whole console on screen, thank you for the fast reply!

**Comment by veeenu** [comment]
You're welcome!
