### ISSUE TITLE
Can't unminimize window sometimes

### ISSUE THREAD

**Issue by veeenu** [veeenu/darksoulsiii-practice-tool#64]
Happens when the game gets minimized when alt-tabbing from full screen.

**Comment by etbrownart** [comment]
[jdsd_dsiii_practice_tool - Copy.log](https://github.com/veeenu/darksoulsiii-practice-tool/files/14673069/jdsd_dsiii_practice_tool.-.Copy.log)

**Comment by veeenu** [comment]
This is caused by the fact that `should_block_events` is true when the menu is open.
