### ISSUE TITLE
Practice tool issue

### ISSUE THREAD

**Issue by Steepstar** [veeenu/darksoulsiii-practice-tool#8]
Dear author of Practice Tool,

I am greatfull for your useful software I've been using for couple of months. It did lots of help to me. 

Regrettably, I faced weird issue. Everything seems to be usual, log look familiar, Tool runs as usually,too. But. The game just do not see it! There is no "Practice tool is active" inscription at the top of the screen like it was before. If you could give me a piece of advice-it would be awesome. 

Thanks in advance and good luck with your future developments.

Sincerely, 
Vadim
 P.S  . Sorry for my english and hello from Russia))) 
![1Practice tool window](https://user-images.githubusercontent.com/99529563/153702668-0d49304d-c3b0-42ff-a351-481854abaeed.png)
![3ds3 window](https://user-images.githubusercontent.com/99529563/153702672-4e2eeb33-d1fc-4ea5-88c6-5f1da8056a81.jpg)
[jdsd_dsiii_practice_tool.log](https://github.com/veeenu/darksoulsiii-practice-tool/files/8053019/jdsd_dsiii_practice_tool.log)

**Comment by veeenu** [comment]
Hey, thank you for your feedback! I'm happy the tool has been helpful :) 

This is something that happens from time to time. I haven't been able to reliably reproduce it so far. Is it happening consistently every single time?
I find it happens less often if I let the game load and get past the "Press Start" prompt before starting the practice tool. On the other hand, it happens more often when starting the tool while the game is still booting up and has a black screen.
Could you please test in both cases and let me know if it is better/worse?
Thank you for reporting the issue! The more feedback and issues we can collect, the better we can make the tool.

**Comment by Steepstar** [comment]
Hey one more time!

Thanks for your quick reply.

I have tried 7 time to run the Tool during "Press Start" screen, 7 times after, and 7 times during the gameplay. It happens all the time. I deleted all mods, I re-install the game, re-install it in original english language- the result is the same. But I remembered one may be important thing. It stopped working after I had used "Debug Menu". Obviously, I deleted it. 

I will think what else it could be and let you know, if I find a solution (may be I need to find some hidden DS3 folders and delete them manually before re-installing or something else).

If you come up with idea how to deal with it, would be great to hear)) 

Thank for the feedback anyway

**Comment by veeenu** [comment]
That makes sense! Debug menu is a separate .exe file with (I assume) different addresses. The tool only explicitly supports a few versions of the vanilla game, adding mods can and will result in undefined behavior like this. Try a completely clean install -- no need to look for hidden folders, everything necessary is under the Steam install folder, except for savefile and configuration files that shouldn't influence these kinds of things anyway.
